/**
 * Sandbox environment seed data — dispensary scenario (Colorado)
 * Creates a fully-populated demo tenant for new customer signups.
 *
 * Run: npx convex run --once createSandboxTenant
 */

import { v4 as uuidv4 } from "uuid";

/**
 * DEMO SCENARIO: "Green Cross Dispensary" — Denver, CO
 * - Single retail location (3000 sq ft)
 * - 100+ SKUs across flower, edibles, concentrates, topicals, accessories
 * - 6 months of activity (Jan–Jun 2025)
 * - Metrc-connected (dummy package tags, simulated sync disabled in sandbox)
 * - Tax: CO Excise 15%, CO Sales 5% — fully calculated
 * - COGS: FIFO costing, monthly allocations
 * - Section 471c election active (retailer, reclassifiable % 40%)
 */

export const createSandboxTenant = async (ctx: any, {
  userId,
  organizationId,
  businessType = "dispensary",
}: {
  userId: string;
  organizationId?: string;
  businessType?: "dispensary" | "cultivator" | "manufacturer";
}) => {
  const companyId = uuidv4();

  // ─── 1. Create Company ──────────────────────────────────────────────────
  const company = await ctx.db.insert("cannabisCompanies", {
    name: businessType === "dispensary" ? "Green Cross Dispensary" :
          businessType === "cultivator" ? "High Plains Cultivation" :
          "Elevation Extracts",
    slug: `demo-${Date.now()}`,
    timezone: "America/Denver",
    states: ["CO"],
    operatorType: businessType,
    primaryOperatorType: businessType,
    defaultAccountingMethod: "accrual",
    accountingMethods: ["cash", "accrual"],
    status: "active",
    // sandbox fields
    sandboxMode: true,
    sandboxCreatedAt: Date.now(),
    sandboxExpiresAt: Date.now() + 14 * 24 * 60 * 60 * 1000, // 14 days
  });

  // ─── 2. Company Admin User ─────────────────────────────────────────────
  await ctx.db.insert("users", {
    clerkId: userId,
    email: `demo-${Date.now()}@tranquillo.demo`,
    name: "Demo Operator",
    companyId,
    role: "admin",
  });

  // ─── 3. Clerk Org Bridge ────────────────────────────────────────────────
  if (organizationId) {
    await ctx.db.insert("organizationCompanies", {
      clerkOrgId: organizationId,
      companyId,
      role: "owner",
    });
  }

  // ─── 4. Location ─────────────────────────────────────────────────────────
  const location = await ctx.db.insert("cannabisLocations", {
    companyId,
    name: "Denver Retail Storefront",
    licenseNumber: "CO-RTL-2025-DEMO001",
    state: "CO",
    city: "Denver",
    isPrimary: true,
    squareFootage: 3000,
  });

  // ─── 5. Metrc License (dummy, sandbox ignores API) ───────────────────────
  await ctx.db.insert("cannabisLicenses", {
    companyId,
    locationId: location,
    licenseType: "Retail",
    state: "CO",
    licenseNumber: "CO-RTL-2025-DEMO001",
    issueDate: "2025-01-01",
    expiryDate: "2026-12-31",
  });

  // ─── 6. Chart of Accounts (cannabis-specific) ───────────────────────────
  await seedChartOfAccounts(ctx, companyId);

  // ─── 7. Inventory: 100+ Products + Batches ──────────────────────────────
  await seedProductsAndInventory(ctx, companyId, location);

  // ─── 8. Counterparties (vendors + customers) ────────────────────────────
  await seedCounterparties(ctx, companyId);

  // ─── 9. Sales Transactions (100) ─────────────────────────────────────────
  await seedSales(ctx, companyId, location);

  // ─── 10. Vendor Invoices (COGS layers) ───────────────────────────────────
  await seedInvoices(ctx, companyId, location);

  // ─── 11. Journal Entries (auto-generated by tax/COGS engine) ────────────
  await seedJournalEntries(ctx, companyId);

  // ─── 12. Tax Profile & Rates ─────────────────────────────────────────────
  await seedTaxProfile(ctx, companyId);

  // ─── 13. Section 471(c) Election ────────────────────────────────────────
  await seedSection471c(ctx, companyId);

  // ─── 14. Reporting Periods (Jan–Jun 2025) ───────────────────────────────
  await seedReportingPeriods(ctx, companyId);

  // ─── 15. Cash Accounts ───────────────────────────────────────────────────
  await seedCashAccounts(ctx, companyId, location);

  // ─── 16. Integration Config (Metrc dummy) ───────────────────────────────
  await ctx.db.insert("integrationConfigs", {
    companyId,
    provider: "metrc",
    realmId: "sandbox-co",
    accessToken: "sandbox-dummy-token",
    refreshToken: "sandbox-dummy-refresh",
    lastSyncAt: null,
    syncSchedule: "manual",
  });

  return { companyId };
};

// ═══════════════════════════════════════════════════════════════════════════
//  Seeder functions
// ═══════════════════════════════════════════════════════════════════════════

async function seedChartOfAccounts(ctx: any, companyId: string) {
  const coa = [
    { code: "1000", name: "Cash", category: "asset", type: "current" },
    { code: "1010", name: "Cash — Vault", category: "asset", type: "current" },
    { code: "1200", name: "Inventory — Cannabis", category: "asset", type: "current" },
    { code: "1300", name: "Prepaid Expenses", category: "asset", type: "current" },
    { code: "2000", name: "Accounts Payable", category: "liability", type: "current" },
    { code: "2100", name: "Sales Tax Payable", category: "liability", type: "current" },
    { code: "2200", name: "Excise Tax Payable", category: "liability", type: "current" },
    { code: "3000", name: "Member Equity", category: "equity", type: "permanent" },
    { code: "4000", name: "Sales Revenue", category: "income", type: "operating" },
    { code: "4010", name: "Excise Tax Revenue", category: "income", type: "operating" },
    { code: "4100", name: "COGS — Cost of Goods Sold", category: "expense", type: "operating" },
    { code: "4110", name: "COGS — 280E Reclassification", category: "expense", type: "operating" },
    { code: "4200", name: "Labor Expense", category: "expense", type: "operating" },
    { code: "4210", name: "Rent Expense", category: "expense", type: "operating" },
    { code: "4220", name: "Utilities", category: "expense", type: "operating" },
    { code: "4300", name: "Marketing & Advertising", category: "expense", type: "operating" },
    { code: "4400", name: "Professional Services", category: "expense", type: "operating" },
    { code: "4500", name: "Supplies & Packaging", category: "expense", type: "operating" },
  ];

  for (const acct of coa) {
    await ctx.db.insert("chartOfAccounts", {
      companyId,
      code: acct.code,
      name: acct.name,
      category: acct.category as any,
      type: acct.type,
      isActive: true,
    });
  }
}

async function seedProductsAndInventory(
  ctx: any,
  companyId: string,
  locationId: string
) {
  // 30 Flower SKUs
  const flowerSkus = Array.from({ length: 30 }, (_, i) => ({
    sku: `FLW-${String(i + 1).padStart(3, "0")}`,
    name: `Premium Flower — ${["Blue Dream", "Girl Scout Cookies", "Gorilla Glue", "Jack Herer", "Pineapple Express", "Sour Diesel", "OG Kush", "Northern Lights", "Wedding Cake", "Gelato"][i % 10]} ${i + 1}g`,
    category: "flower",
    unitOfMeasure: "gram",
  }));

  // 20 Edible SKUs
  const edibleSkus = Array.from({ length: 20 }, (_, i) => ({
    sku: `EDB-${String(i + 1).padStart(3, "0")}`,
    name: `Gummy — ${["Sour Worms", "Peach Rings", "Watermelon", "Mixed Berry", "Citrus Burst"][i % 5]} ${(i + 1) * 10}mg`,
    category: "edibles",
    unitOfMeasure: "each",
  }));

  // 20 Concentrate SKUs
  const concentrateSkus = Array.from({ length: 20 }, (_, i) => ({
    sku: `CON-${String(i + 1).padStart(3, "0")}`,
    name: ` concentrates — ${["Shatter", "Wax", "Live Resin", "Distillate"][i % 4]} ${(i + 1) * 0.5}g`,
    category: "concentrates",
    unitOfMeasure: "gram",
  }));

  // 10 Topical SKUs
  const topicalSkus = Array.from({ length: 10 }, (_, i) => ({
    sku: `TOP-${String(i + 1).padStart(3, "0")}`,
    name: `Topical Cream — ${["Pain Relief", "Anti-Inflammatory", "Recovery"][i % 3]} ${30 + i * 5}ml`,
    category: "topicals",
    unitOfMeasure: "ml",
  }));

  // 20 Accessory SKUs (non-cannabis)
  const accessorySkus = Array.from({ length: 20 }, (_, i) => ({
    sku: `ACC-${String(i + 1).padStart(3, "0")}`,
    name: `Vape Pen — ${["Battery", "Charger", "Cartridge", "Case"][i % 4]} #${i + 1}`,
    category: "accessories",
    unitOfMeasure: "each",
  }));

  const allProducts = [...flowerSkus, ...edibleSkus, ...concentrateSkus, ...topicalSkus, ...accessorySkus];

  // Insert all products
  const productIds: string[] = [];
  for (const p of allProducts) {
    const id = await ctx.db.insert("products", {
      companyId,
      sku: p.sku,
      name: p.name,
      category: p.category,
      unitOfMeasure: p.unitOfMeasure,
      isActive: true,
      metrcPackageId: null, // sandbox — no Metrc
    });
    productIds.push(id);
  }

  // Create inventory batches (FIFO layers) — one per product
  for (const productId of productIds) {
    await ctx.db.insert("inventoryBatches", {
      companyId,
      productId,
      locationId,
      packageTag: `SANDBOX-${productId.slice(0, 8)}`,
      quantityOnHand: Math.floor(Math.random() * 50) + 10,
      receivedAt: "2025-01-15",
      unitCost: Math.random() * 20 + 5, // $5–25 cost
    });
  }
}

async function seedCounterparties(ctx: any, companyId: string) {
  // Vendors
  const vendors = [
    "Green Source Supply",
    "CannaCraft Distributors",
    "Elevated Extracts",
    "Golden Triangle Farm",
    "Rocky Mountain Rec",
  ];
  for (const v of vendors) {
    await ctx.db.insert("counterparties", {
      companyId,
      name: v,
      type: "vendor",
    });
  }

  // Customers (walk-ins — for sales demo)
  for (let i = 1; i <= 20; i++) {
    await ctx.db.insert("counterparties", {
      companyId,
      name: `Walk-in Customer #${i}`,
      type: "customer",
    });
  }
}

async function seedSales(ctx: any, companyId: string, locationId: string) {
  // Generate 100 sales across Jan–Jun 2025
  const products = await ctx.db.query("products").filter(q => q.eq(q.field("companyId"), companyId)).collect();

  for (let i = 0; i < 100; i++) {
    const saleDate = randomDate(new Date("2025-01-01"), new Date("2025-06-30"));
    const product = products[Math.floor(Math.random() * products.length)];
    const unitPrice = Math.floor(Math.random() * 80) + 20; // $20–100 retail
    const quantity = Math.floor(Math.random() * 3) + 1;
    const subtotal = unitPrice * quantity;
    const taxAmount = subtotal * 0.15 + subtotal * 0.05; // CO excise + sales

    const transaction = await ctx.db.insert("transactions", {
      companyId,
      locationId,
      transactionDate: saleDate.toISOString().split("T")[0],
      description: `Sale #${1000 + i} — ${product.name}`,
      totalAmount: subtotal + taxAmount,
      status: "posted",
    });

    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "4000"), // Sales Revenue
      credit: subtotal,
    });

    // Tax breakdown
    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "4010"), // Excise Tax Rev
      credit: Math.round(subtotal * 0.15 * 100) / 100,
    });
    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "2100"), // Sales Tax Payable
      credit: Math.round(subtotal * 0.05 * 100) / 100,
    });

    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "1000"), // Cash
      debit: Math.round((subtotal + taxAmount) * 100) / 100,
    });
  }
}

async function seedInvoices(ctx: any, companyId: string, locationId: string) {
  // Vendor purchase invoices with FIFO-relevant unit costs
  const vendors = await ctx.db.query("counterparties")
    .filter(q => q.eq(q.field("companyId"), companyId))
    .filter(q => q.eq(q.field("type"), "vendor"))
    .collect();

  const products = await ctx.db.query("products").filter(q => q.eq(q.field("companyId"), companyId)).collect();

  for (let i = 0; i < 50; i++) {
    const invoiceDate = randomDate(new Date("2025-01-01"), new Date("2025-06-30"));
    const vendor = vendors[Math.floor(Math.random() * vendors.length)];
    const product = products[Math.floor(Math.random() * products.length)];
    const quantity = Math.floor(Math.random() * 20) + 1;
    const unitCost = Math.random() * 15 + 3; // $3–18 wholesale

    const transaction = await ctx.db.insert("transactions", {
      companyId,
      locationId,
      transactionDate: invoiceDate.toISOString().split("T")[0],
      description: `Invoice #${5000 + i} — ${vendor.name}`,
      totalAmount: Math.round(quantity * unitCost * 100) / 100,
      status: "posted",
    });

    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "2000"), // AP
      credit: Math.round(quantity * unitCost * 100) / 100,
    });

    await ctx.db.insert("transactionLines", {
      transactionId: transaction,
      accountId: await lookupAccountId(ctx, companyId, "1200"), // Inventory
      debit: Math.round(quantity * unitCost * 100) / 100,
    });

    // Update batch quantity
    const batches = await ctx.db.query("inventoryBatches")
      .filter(q => q.eq(q.field("companyId"), companyId))
      .filter(q => q.eq(q.field("productId"), product))
      .collect();
    if (batches.length > 0) {
      const batch = batches[0];
      await ctx.db.patch(batch._id, { quantityOnHand: batch.quantityOnHand + quantity });
    }
  }
}

async function seedJournalEntries(ctx: any, companyId: string) {
  // One manual JE per month (typical accrual entries)
  const entries = [
    { date: "2025-01-31", desc: "Monthly accrual — rent", debit: "4210", credit: "2000", amount: 3500 },
    { date: "2025-02-28", desc: "Monthly accrual — utilities", debit: "4220", credit: "2000", amount: 1200 },
    { date: "2025-03-31", desc: "Monthly accrual — marketing", debit: "4300", credit: "2000", amount: 2500 },
    { date: "2025-04-30", desc: "Monthly accrual — professional services", debit: "4400", credit: "2000", amount: 1800 },
  ];

  for (const e of entries) {
    const txn = await ctx.db.insert("transactions", {
      companyId,
      transactionDate: e.date,
      description: e.desc,
      totalAmount: e.amount,
      status: "posted",
    });

    await ctx.db.insert("transactionLines", {
      transactionId: txn,
      accountId: await lookupAccountId(ctx, companyId, e.debit),
      debit: e.amount,
    });
    await ctx.db.insert("transactionLines", {
      transactionId: txn,
      accountId: await lookupAccountId(ctx, companyId, e.credit),
      credit: e.amount,
    });
  }
}

async function seedTaxProfile(ctx: any, companyId: string) {
  // Get CO state jurisdiction
  const jur = await ctx.db.query("taxJurisdictions")
    .filter(q => q.eq(q.field("stateCode"), "CO"))
    .first();

  await ctx.db.insert("taxProfiles", {
    companyId,
    state: "CO",
    primaryJurisdictionId: jur?._id,
    nexusStates: ["CO"],
    filingCalendar: { excise: "quarterly", sales: "monthly" },
    taxTypesEnabled: { excise: true, sales: true },
  });
}

async function seedSection471c(ctx: any, companyId: string) {
  await ctx.db.insert("section471cElections", {
    companyId,
    elected: true,
    electionDate: "2025-01-01",
    taxYear: 2025,
    priorYear1: 2024,
    priorYear2: 2023,
    reclassifiablePct: { default: 40 },
    capitalizationThreshold: 5000,
    capitalizationPolicyDescription: "All cannabis inventory costs (excise + COGS) capitalized per IRC §471c",
    uczMidpoint: 12,
    notes: "Sandbox demo election",
  });
}

async function seedReportingPeriods(ctx: any, companyId: string) {
  const periods = [
    { label: "Jan 2025", start: "2025-01-01", end: "2025-01-31", status: "closed" },
    { label: "Feb 2025", start: "2025-02-01", end: "2025-02-28", status: "closed" },
    { label: "Mar 2025", start: "2025-03-01", end: "2025-03-31", status: "closed" },
    { label: "Apr 2025", start: "2025-04-01", end: "2025-04-30", status: "open" },
    { label: "May 2025", start: "2025-05-01", end: "2025-05-31", status: "open" },
    { label: "Jun 2025", start: "2025-06-01", end: "2025-06-30", status: "open" },
  ];

  for (const p of periods) {
    await ctx.db.insert("reportingPeriods", {
      companyId,
      label: p.label,
      startDate: p.start,
      endDate: p.end,
      status: p.status as any,
    });
  }
}

async function seedCashAccounts(ctx: any, companyId: string, locationId: string) {
  await ctx.db.insert("cashAccounts", {
    companyId,
    locationId,
    name: "Main Vault",
    type: "vault",
    active: true,
  });

  await ctx.db.insert("cashAccounts", {
    companyId,
    locationId,
    name: "POS Cash Drawer",
    type: "drawer",
    active: true,
  });

  await ctx.db.insert("cashAccounts", {
    companyId,
    locationId: null,
    name: "Bank — Chase",
    type: "bank_clearing",
    active: true,
  });
}

// ═══════════════════════════════════════════════════════════════════════════
//  Helpers
// ═══════════════════════════════════════════════════════════════════════════

function randomDate(start: Date, end: Date): Date {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

async function lookupAccountId(ctx: any, companyId: string, code: string): Promise<string> {
  const acct = await ctx.db.query("chartOfAccounts")
    .filter(q => q.eq(q.field("companyId"), companyId))
    .filter(q => q.eq(q.field("code"), code))
    .first();
  if (!acct) throw new Error(`Account ${code} not found`);
  return acct._id;
}

export default createSandboxTenant;

